---
version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    command: "true"
    volumes:
      - ~/.config:/app/.config
    environment:
      - HUB_SSH_KEY_BASE64
      - HUB_REPO_URL
      - HUB_BRANCH_SOURCE
      - HUB_BRANCH_PUBLISH
      - GCLOUD_SERVICE_KEY

